var unfallursache = {
"1": 'Alkoholeinfluß',
"2": 'Einfluß anderer berauschender Mittel (z.B. Drogen, Rauschgift)',
"3": 'Übermüdung',
"4": 'Sonstige körperliche oder geistige Mängel',
"8": 'Falschfahrt auf Straßen mit nach Fahrtrichtung getrennten Fahrbahnen',
"9": 'Benutzung der Fahrbahn entgegen der vorgeschriebenen Fahrtrichtung in anderen Fällen',
"10": 'Benutzung der falschen Fahrbahn (auch Richtungsfahrbahn) oder verbotswidrige Benutzung anderer Straßenteile',
"11": 'Verstoß gegen das Rechtsfahrgebot',
"12": 'Nicht angepaßte Geschwindigkeit mit gleichzeitigem Überschreiten der zulässigen Höchstgeschwindigkeit',
"13": 'Nicht angepaßte Geschwindigkeit in anderen Fällen',
"14": 'Ungenügender Sicherheitsabstand',
"15": 'Starkes Bremsen des Vorausfahrenden ohne zwingenden Grund',
"16": 'Unzulässiges Rechtsüberholen',
"17": 'Überholen trotz Gegenverkehr',
"18": 'Überholen trotz unklarer Verkehrslage',
"19": 'Überholen trotz unzureichender Sichtverhältnisse',
"20": 'Überholen ohne Beachtung des nachfolgenden Verkehrs und/oder ohne rechtzeitige und deutliche Ankündigung des Ausscherens',
"21": 'Fehler beim Wiedereinordnen nach rechts',
"22": 'Sonstige Fehler beim Überholen',
"23": 'Fehler beim Überholtwerden',
"24": 'Nichtbeachten des Vorranges entgegenkommender Fahrzeuge beim Vorbeifahren an haltenden Fahrzeugen, Absperrungen oder Hindernissen',
"25": 'Nichtbeachten des nachfolgenden Verkehrs beim Vorbeifahren an haltenden Fahrzeugen',
"26": 'Fehlerhaftes Wechseln des Fahrstreifens beim Nebeneinanderfahren',
"27": 'Nichtbeachten der Regel "rechts vor links"',
"28": 'Nichtbeachten der die Vorfahrt regelnden Verkehrszeichen',
"29": 'Nichtbeachten der Vorfahrt des durchgehenden Verkehrs auf Autobahnen oder Kraftfahrstraßen',
"30": 'Nichtbeachten der Vorfahrt durch Fahrzeuge, die aus Feld- und Waldwegen kommen',
"31": 'Nichtbeachten der Verkehrsregelung durch Polizeibeamte oder Lichtzeichen',
"32": 'Nichtbeachten des Vorranges entgegenkommender Fahrzeuge',
"33": 'Nichtbeachten des Vorranges von Schienenfahrzeugen an Bahnübergängen',
"34": 'Fehler beim Abbiegen (§ 9 StVO) nach rechts',
"35": 'Fehler beim Abbiegen (§ 9 StVO) nach links',
"36": 'Fehler beim Wenden oder Rückwärtsfahren',
"37": 'Fehler beim Einfahren in den fließenden Verkehr',
"38": 'Falsches Verhalten gegenüber Fußgängern an Fußgängerüberwegen',
"39": 'Falsches Verhalten gegenüber Fußgängern an Fußgängerfurten',
"40": 'Falsches Verhalten gegenüber Fußgängern beim Abbiegen',
"41": 'Falsches Verhalten gegenüber Fußgängern an Haltestellen',
"42": 'Falsches Verhalten gegenüber Fußgängern an anderen Stellen',
"43": 'Unzulässiges Halten oder Parken',
"44": 'Mangelnde Sicherung haltender oder liegengebliebener Fahrzeuge und von Unfallstellen',
"45": 'Verkehrswidriges Verhalten beim Ein- und Aussteigen, Be- und Entladen',
"46": 'Nichtbeachten der Beleuchtungsvorschriften',
"47": 'Überladung, Überbesetzung',
"48": 'Unzureichend gesicherte Ladung oder Fahrzeugzubehörteile',
"49": 'Andere Fehler beim Fahrzeugführer',
"50": 'Mängel an der Beleuchtung',
"51": 'Mängel an der Bereifung',
"52": 'Mängel an den Bremsen',
"53": 'Mängel an der Lenkung',
"54": 'Mängel an der Zugvorrichtung',
"55": 'andere Mängel',
"60": 'Falsches Verhalten beim Überschreiten der Fahrbahn an Stellen, an denen der Fußgängerverkehr durch Polizeibeamte oder Lichtzeichen geregelt war',
"61": 'Falsches Verhalten beim Überschreiten der Fahrbahn auf Fußgängerüberwegen ohne Verkehrsregelung',
"62": 'Falsches Verhalten beim Überschreiten der Fahrbahn in der Nähe von Kreuzungen oder Einmündungen',
"63": 'Falsches Verhalten beim Überschreiten der Fahrbahn durch plötzliches Hervortreten hinter Sichthindernissen',
"64": 'Falsches Verhalten beim Überschreiten der Fahrbahn ohne auf den Fahrzeugverkehr zu achten',
"65": 'Falsches Verhalten beim Überschreiten der Fahrbahn durch sonstiges falsches Verhalten',
"66": 'Nichtbenutzen des Gehweges',
"67": 'Nichtbenutzen der vorgeschriebenen Straßenseite',
"68": 'Spielen auf oder neben der Fahrbahn',
"69": 'Andere Fehler der Fußgänger',
"70": 'Verunreinigung durch ausgelaufenes Öl',
"71": 'Andere Verunreinigungen durch Straßenbenutzer',
"72": 'Schnee, Eis',
"73": 'Regen',
"74": 'Andere Einflüsse (u.a. Laub, angeschwemmter Lehm)',
"75": 'Spurrillen, im Zusammenhang mit Regen, Schnee oder Eis',
"76": 'Anderer Zustand der Straße',
"77": 'Nicht ordnungsgemäßer Zustand der Verkehrszeichen oder -einrichtung',
"78": 'Mangelhafte Beleuchtung der Straße',
"79": 'Mangelhafte Sicherung von Bahnübergängen',
"80": 'Sichtbehinderung durch Nebel',
"81": 'Sichtbehinderung durch starken Regen, Hagel, Schneegestöber',
"82": 'Sichtbehinderung durch blendende Sonne',
"83": 'Seitenwind',
"84": 'Unwetter oder sonstige Witterungseinflüsse',
"85": 'Nicht oder unzureichend gesicherte Arbeitsstelle auf der Fahrbahn',
"86": 'Wild auf der Fahrbahn',
"87": 'Anderes Tier auf der Fahrbahn',
"88": 'Sonstiges Hindernis auf der Fahrbahn',
"89": 'Sonstige Ursachen'
};
