#!/usr/bin/perl -w

use strict;
use Data::Dumper;
use utf8;
use HTML::TreeBuilder::XPath;
use open IO => ":encoding(utf-8)";
use open ':std';
use JSON;

my $result;

foreach my $fname (@ARGV) {
	#print "fname $fname\n";
	my $num=$fname;
	$num =~ s/^description.|\-.*$//g;

	my $tree = HTML::TreeBuilder::XPath->new; # empty tree
	$tree->parse_file($fname);

	# div id="unka-detailboxright"
	my $n=$tree->findvalue('/html/body//div[@id="unka-detailboxright"]');
	my @a = split(/.rtlichkeit . Verkehrsvorgang:|Beschreibung:\s*|Kommentar:\s*|Stichpunkte|Kategorie/, $n);
	my @r=map { s/^\s+//; s/\-{2,}//; s/^\s+$//; $_;} @a;

	my $l;
	if ($r[1] ne '') {
		$l->{ort}=$r[1];
	}
	if ($r[2] ne '') {
		$l->{beschreibung}=$r[2];
	}
	if ($r[3] ne '') {
		$l->{kommentar}=$r[3];
	}

	$result->{$num}=$l;
}

print "var unfalltypen=" . to_json( $result, { ascii => 0, pretty => 0 } );
